[servers]
cachyos-node-01 ansible_host=192.108.10.101 ansible_user=admin ansible_port=22
kernel-worker-02 ansible_host=192.108.10.102 ansible_user=admin ansible_port=22

[servers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'